// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AccountLoginForm: typeof import('./src/components/AccountLoginForm.vue')['default']
    LoginPage: typeof import('./src/components/LoginPage.vue')['default']
    PhoneLoginForm: typeof import('./src/components/PhoneLoginForm.vue')['default']
    QRCodeLoginForm: typeof import('./src/components/QRCodeLoginForm.vue')['default']
    RegisterForm: typeof import('./src/components/RegisterForm.vue')['default']
  }
}

export { }
